# Generated by Django 3.2 on 2021-04-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0120_bookmarklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='use_fractions',
            field=models.BooleanField(default=False),
        ),
    ]
