# Generated by Django 4.2.7 on 2023-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0205_alter_food_fdc_id_alter_propertytype_fdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='ingredient_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='use_fractions',
            field=models.BooleanField(default=True),
        ),
    ]
