# Generated by Django 5.2.15 on 2026-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0247_recipe_image_squashed_0249_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='nav_bg_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('TANDOOR', 'Tandoor'), ('BOOTSTRAP', 'Bootstrap'), ('DARKLY', 'Darkly'), ('FLATLY', 'Flatly'), ('SUPERHERO', 'Superhero'), ('TANDOOR_DARK', 'Tandoor Dark (INCOMPLETE)'), ('CERULEAN', 'Cerulean'), ('SLATE', 'Slate')], default='TANDOOR', max_length=128),
        ),
    ]
