# Generated by Django 5.2.15 on 2026-08-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0249_food_shelf_life_days_food_shopping_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ('pk',)},
        ),
    ]
