# Generated by Django 5.2.15 on 2026-08-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0250_household_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='cookbook.userfile'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='crop_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
