# Generated by Django 5.2.15 on 2026-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0251_food_image_and_userfile_crop_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shelf_life_days_frozen',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='shelf_life_days_opened',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='opened_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='booking_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('move', 'Move'), ('open', 'Open')], default='add', max_length=10),
        ),
    ]
