# Generated by Django 5.2.15 on 2026-08-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0252_recipebook_image'),
        ('cookbook', '0253_spacebackup'),
    ]

    operations = [
    ]
