# Generated by Django 5.2.16 on 2026-08-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0254_merge_0252_recipebook_image_0253_spacebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_recipe_scale',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
    ]
