/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ConnectorConfigUrl
 * 
 * @export
 */
export type ConnectorConfigUrl = string;

export function ConnectorConfigUrlFromJSON(json: any): ConnectorConfigUrl {
    return ConnectorConfigUrlFromJSONTyped(json, false);
}

export function ConnectorConfigUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorConfigUrl {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ConnectorConfigUrlToJSON(json: any): any {
    return ConnectorConfigUrlToJSONTyped(json, false);
}

export function ConnectorConfigUrlToJSONTyped(value?: ConnectorConfigUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

