/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RotateEnum } from './RotateEnum';
import {
    RotateEnumFromJSON,
    RotateEnumFromJSONTyped,
    RotateEnumToJSON,
    RotateEnumToJSONTyped,
} from './RotateEnum';

/**
 * Schema-only shape for the ``crop_data``/``image_crop_data`` JSONField
 * on UserFile and RecipeImage. Never used for actual (de)serialization -
 * both fields stay plain JSONField with their own imperative validation.
 * UserFileSerializer.check_crop_data clamps x/y/width/height to [0,100];
 * RecipeImageSerializer.check_crop_data deliberately allows negative/>100
 * values (soft-clamped to [-1000,1000]/<=2000) to support non-square crops
 * of non-square images. No min/max is declared here since the two models'
 * rules genuinely differ - a single shared schema can't assert either
 * model's range without misrepresenting the other. This exists purely so
 * drf-spectacular emits a real object schema instead of `any`, so the
 * generated OpenAPI client can serialize it (see anyToJSON regression).
 * @export
 * @interface CropData
 */
export interface CropData {
    /**
     * 
     * @type {number}
     * @memberof CropData
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof CropData
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof CropData
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof CropData
     */
    height?: number;
    /**
     * 
     * @type {RotateEnum}
     * @memberof CropData
     */
    rotate?: RotateEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CropData
     */
    fit?: boolean;
}



/**
 * Check if a given object implements the CropData interface.
 */
export function instanceOfCropData(value: object): value is CropData {
    return true;
}

export function CropDataFromJSON(json: any): CropData {
    return CropDataFromJSONTyped(json, false);
}

export function CropDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CropData {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'rotate': json['rotate'] == null ? undefined : RotateEnumFromJSON(json['rotate']),
        'fit': json['fit'] == null ? undefined : json['fit'],
    };
}

export function CropDataToJSON(json: any): CropData {
    return CropDataToJSONTyped(json, false);
}

export function CropDataToJSONTyped(value?: CropData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
        'rotate': RotateEnumToJSON(value['rotate']),
        'fit': value['fit'],
    };
}

