/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawDownItem } from './DrawDownItem';
import {
    DrawDownItemFromJSON,
    DrawDownItemFromJSONTyped,
    DrawDownItemToJSON,
    DrawDownItemToJSONTyped,
} from './DrawDownItem';

/**
 * 
 * @export
 * @interface DrawDown
 */
export interface DrawDown {
    /**
     * 
     * @type {Array<DrawDownItem>}
     * @memberof DrawDown
     */
    items: Array<DrawDownItem>;
}

/**
 * Check if a given object implements the DrawDown interface.
 */
export function instanceOfDrawDown(value: object): value is DrawDown {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function DrawDownFromJSON(json: any): DrawDown {
    return DrawDownFromJSONTyped(json, false);
}

export function DrawDownFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawDown {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DrawDownItemFromJSON)),
    };
}

export function DrawDownToJSON(json: any): DrawDown {
    return DrawDownToJSONTyped(json, false);
}

export function DrawDownToJSONTyped(value?: DrawDown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DrawDownItemToJSON)),
    };
}

