/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One row of a Use-up draw-down request (FR-G): the food and its new total amount.
 * 
 * ``unit`` scopes the reduction to lots in that unit (DEC-2) — deliberately no default, so an
 * OMITTED key (legacy all-lots behavior) stays distinguishable from an explicit ``null`` (scope
 * to unit-less lots). ``new_unit`` re-declares the remainder in a different unit (DEC-3:
 * "started with 1 gallon, now have 1 cup").
 * @export
 * @interface DrawDownItem
 */
export interface DrawDownItem {
    /**
     * 
     * @type {number}
     * @memberof DrawDownItem
     */
    food: number;
    /**
     * 
     * @type {number}
     * @memberof DrawDownItem
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof DrawDownItem
     */
    unit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DrawDownItem
     */
    newUnit?: number | null;
}

/**
 * Check if a given object implements the DrawDownItem interface.
 */
export function instanceOfDrawDownItem(value: object): value is DrawDownItem {
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function DrawDownItemFromJSON(json: any): DrawDownItem {
    return DrawDownItemFromJSONTyped(json, false);
}

export function DrawDownItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawDownItem {
    if (json == null) {
        return json;
    }
    return {
        
        'food': json['food'],
        'amount': json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'newUnit': json['new_unit'] == null ? undefined : json['new_unit'],
    };
}

export function DrawDownItemToJSON(json: any): DrawDownItem {
    return DrawDownItemToJSONTyped(json, false);
}

export function DrawDownItemToJSONTyped(value?: DrawDownItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': value['food'],
        'amount': value['amount'],
        'unit': value['unit'],
        'new_unit': value['newUnit'],
    };
}

