/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodFromRecipe
 */
export interface FoodFromRecipe {
    /**
     * 
     * @type {number}
     * @memberof FoodFromRecipe
     */
    recipe: number;
    /**
     * 
     * @type {string}
     * @memberof FoodFromRecipe
     */
    name?: string;
}

/**
 * Check if a given object implements the FoodFromRecipe interface.
 */
export function instanceOfFoodFromRecipe(value: object): value is FoodFromRecipe {
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    return true;
}

export function FoodFromRecipeFromJSON(json: any): FoodFromRecipe {
    return FoodFromRecipeFromJSONTyped(json, false);
}

export function FoodFromRecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodFromRecipe {
    if (json == null) {
        return json;
    }
    return {
        
        'recipe': json['recipe'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function FoodFromRecipeToJSON(json: any): FoodFromRecipe {
    return FoodFromRecipeToJSONTyped(json, false);
}

export function FoodFromRecipeToJSONTyped(value?: FoodFromRecipe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipe': value['recipe'],
        'name': value['name'],
    };
}

