/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFileView } from './UserFileView';
import {
    UserFileViewFromJSON,
    UserFileViewFromJSONTyped,
    UserFileViewToJSON,
    UserFileViewToJSONTyped,
} from './UserFileView';
import type { ShoppingList } from './ShoppingList';
import {
    ShoppingListFromJSON,
    ShoppingListFromJSONTyped,
    ShoppingListToJSON,
    ShoppingListToJSONTyped,
} from './ShoppingList';
import type { SupermarketCategory } from './SupermarketCategory';
import {
    SupermarketCategoryFromJSON,
    SupermarketCategoryFromJSONTyped,
    SupermarketCategoryToJSON,
    SupermarketCategoryToJSONTyped,
} from './SupermarketCategory';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    UnitToJSONTyped,
} from './Unit';

/**
 * 
 * @export
 * @interface FoodShopping
 */
export interface FoodShopping {
    /**
     * 
     * @type {number}
     * @memberof FoodShopping
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodShopping
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoodShopping
     */
    pluralName?: string | null;
    /**
     * 
     * @type {SupermarketCategory}
     * @memberof FoodShopping
     */
    readonly supermarketCategory: SupermarketCategory;
    /**
     * 
     * @type {Array<ShoppingList>}
     * @memberof FoodShopping
     */
    readonly shoppingLists: Array<ShoppingList>;
    /**
     * 
     * @type {string}
     * @memberof FoodShopping
     */
    readonly inInventory: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FoodShopping
     */
    readonly earliestExpiry: Date | null;
    /**
     * 
     * @type {number}
     * @memberof FoodShopping
     */
    shoppingAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FoodShopping
     */
    shelfLifeDays?: number | null;
    /**
     * 
     * @type {Unit}
     * @memberof FoodShopping
     */
    preferredShoppingUnit?: Unit | null;
    /**
     * 
     * @type {UserFileView}
     * @memberof FoodShopping
     */
    readonly foodImage: UserFileView | null;
    /**
     * 
     * @type {boolean}
     * @memberof FoodShopping
     */
    readonly substituteOnhand: boolean;
}

/**
 * Check if a given object implements the FoodShopping interface.
 */
export function instanceOfFoodShopping(value: object): value is FoodShopping {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('supermarketCategory' in value) || value['supermarketCategory'] === undefined) return false;
    if (!('shoppingLists' in value) || value['shoppingLists'] === undefined) return false;
    if (!('inInventory' in value) || value['inInventory'] === undefined) return false;
    if (!('earliestExpiry' in value) || value['earliestExpiry'] === undefined) return false;
    if (!('foodImage' in value) || value['foodImage'] === undefined) return false;
    if (!('substituteOnhand' in value) || value['substituteOnhand'] === undefined) return false;
    return true;
}

export function FoodShoppingFromJSON(json: any): FoodShopping {
    return FoodShoppingFromJSONTyped(json, false);
}

export function FoodShoppingFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodShopping {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
        'supermarketCategory': SupermarketCategoryFromJSON(json['supermarket_category']),
        'shoppingLists': ((json['shopping_lists'] as Array<any>).map(ShoppingListFromJSON)),
        'inInventory': json['in_inventory'],
        'earliestExpiry': (json['earliest_expiry'] == null ? null : new Date(json['earliest_expiry'])),
        'shoppingAmount': json['shopping_amount'] == null ? undefined : json['shopping_amount'],
        'shelfLifeDays': json['shelf_life_days'] == null ? undefined : json['shelf_life_days'],
        'preferredShoppingUnit': json['preferred_shopping_unit'] == null ? undefined : UnitFromJSON(json['preferred_shopping_unit']),
        'foodImage': UserFileViewFromJSON(json['food_image']),
        'substituteOnhand': json['substitute_onhand'],
    };
}

export function FoodShoppingToJSON(json: any): FoodShopping {
    return FoodShoppingToJSONTyped(json, false);
}

export function FoodShoppingToJSONTyped(value?: Omit<FoodShopping, 'supermarket_category'|'shopping_lists'|'in_inventory'|'earliest_expiry'|'food_image'|'substitute_onhand'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'plural_name': value['pluralName'],
        'shopping_amount': value['shoppingAmount'],
        'shelf_life_days': value['shelfLifeDays'],
        'preferred_shopping_unit': UnitToJSON(value['preferredShoppingUnit']),
    };
}

