/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type InviteLinkEmail
 * 
 * @export
 */
export type InviteLinkEmail = string;

export function InviteLinkEmailFromJSON(json: any): InviteLinkEmail {
    return InviteLinkEmailFromJSONTyped(json, false);
}

export function InviteLinkEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteLinkEmail {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function InviteLinkEmailToJSON(json: any): any {
    return InviteLinkEmailToJSONTyped(json, false);
}

export function InviteLinkEmailToJSONTyped(value?: InviteLinkEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

