/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpaceBackup } from './SpaceBackup';
import {
    SpaceBackupFromJSON,
    SpaceBackupFromJSONTyped,
    SpaceBackupToJSON,
    SpaceBackupToJSONTyped,
} from './SpaceBackup';

/**
 * 
 * @export
 * @interface PaginatedSpaceBackupList
 */
export interface PaginatedSpaceBackupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSpaceBackupList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSpaceBackupList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSpaceBackupList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SpaceBackup>}
     * @memberof PaginatedSpaceBackupList
     */
    results: Array<SpaceBackup>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedSpaceBackupList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedSpaceBackupList interface.
 */
export function instanceOfPaginatedSpaceBackupList(value: object): value is PaginatedSpaceBackupList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSpaceBackupListFromJSON(json: any): PaginatedSpaceBackupList {
    return PaginatedSpaceBackupListFromJSONTyped(json, false);
}

export function PaginatedSpaceBackupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSpaceBackupList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SpaceBackupFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedSpaceBackupListToJSON(json: any): PaginatedSpaceBackupList {
    return PaginatedSpaceBackupListToJSONTyped(json, false);
}

export function PaginatedSpaceBackupListToJSONTyped(value?: PaginatedSpaceBackupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SpaceBackupToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

