/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortableDataExportRequest
 */
export interface PortableDataExportRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PortableDataExportRequest
     */
    includeFoods?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PortableDataExportRequest
     */
    includeKeywords?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PortableDataExportRequest
     */
    includeBooks?: boolean;
}

/**
 * Check if a given object implements the PortableDataExportRequest interface.
 */
export function instanceOfPortableDataExportRequest(value: object): value is PortableDataExportRequest {
    return true;
}

export function PortableDataExportRequestFromJSON(json: any): PortableDataExportRequest {
    return PortableDataExportRequestFromJSONTyped(json, false);
}

export function PortableDataExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortableDataExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'includeFoods': json['include_foods'] == null ? undefined : json['include_foods'],
        'includeKeywords': json['include_keywords'] == null ? undefined : json['include_keywords'],
        'includeBooks': json['include_books'] == null ? undefined : json['include_books'],
    };
}

export function PortableDataExportRequestToJSON(json: any): PortableDataExportRequest {
    return PortableDataExportRequestToJSONTyped(json, false);
}

export function PortableDataExportRequestToJSONTyped(value?: PortableDataExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'include_foods': value['includeFoods'],
        'include_keywords': value['includeKeywords'],
        'include_books': value['includeBooks'],
    };
}

