/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortableDataImportRequest
 */
export interface PortableDataImportRequest {
    /**
     * 
     * @type {string}
     * @memberof PortableDataImportRequest
     */
    mode: string;
    /**
     * 
     * @type {any}
     * @memberof PortableDataImportRequest
     */
    _export: any | null;
    /**
     * 
     * @type {string}
     * @memberof PortableDataImportRequest
     */
    mergePolicy?: string;
}

/**
 * Check if a given object implements the PortableDataImportRequest interface.
 */
export function instanceOfPortableDataImportRequest(value: object): value is PortableDataImportRequest {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('_export' in value) || value['_export'] === undefined) return false;
    return true;
}

export function PortableDataImportRequestFromJSON(json: any): PortableDataImportRequest {
    return PortableDataImportRequestFromJSONTyped(json, false);
}

export function PortableDataImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortableDataImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        '_export': json['export'],
        'mergePolicy': json['merge_policy'] == null ? undefined : json['merge_policy'],
    };
}

export function PortableDataImportRequestToJSON(json: any): PortableDataImportRequest {
    return PortableDataImportRequestToJSONTyped(json, false);
}

export function PortableDataImportRequestToJSONTyped(value?: PortableDataImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'export': value['_export'],
        'merge_policy': value['mergePolicy'],
    };
}

