/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0` - 0
 * * `90` - 90
 * * `180` - 180
 * * `270` - 270
 * @export
 */
export const RotateEnum = {
    NUMBER_0: 0,
    NUMBER_90: 90,
    NUMBER_180: 180,
    NUMBER_270: 270
} as const;
export type RotateEnum = typeof RotateEnum[keyof typeof RotateEnum];


export function instanceOfRotateEnum(value: any): boolean {
    for (const key in RotateEnum) {
        if (Object.prototype.hasOwnProperty.call(RotateEnum, key)) {
            if (RotateEnum[key as keyof typeof RotateEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RotateEnumFromJSON(json: any): RotateEnum {
    return RotateEnumFromJSONTyped(json, false);
}

export function RotateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateEnum {
    return json as RotateEnum;
}

export function RotateEnumToJSON(value?: RotateEnum | null): any {
    return value as any;
}

export function RotateEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): RotateEnum {
    return value as RotateEnum;
}

