/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpaceBackup
 */
export interface SpaceBackup {
    /**
     * 
     * @type {number}
     * @memberof SpaceBackup
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SpaceBackup
     */
    readonly running: boolean;
    /**
     * 
     * @type {string}
     * @memberof SpaceBackup
     */
    readonly msg: string;
    /**
     * 
     * @type {number}
     * @memberof SpaceBackup
     */
    readonly totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof SpaceBackup
     */
    readonly processedItems: number;
    /**
     * 
     * @type {string}
     * @memberof SpaceBackup
     */
    readonly file: string | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceBackup
     */
    readonly fileSizeKb: number;
    /**
     * 
     * @type {number}
     * @memberof SpaceBackup
     */
    readonly createdBy: number;
    /**
     * 
     * @type {Date}
     * @memberof SpaceBackup
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the SpaceBackup interface.
 */
export function instanceOfSpaceBackup(value: object): value is SpaceBackup {
    if (!('running' in value) || value['running'] === undefined) return false;
    if (!('msg' in value) || value['msg'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('processedItems' in value) || value['processedItems'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('fileSizeKb' in value) || value['fileSizeKb'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SpaceBackupFromJSON(json: any): SpaceBackup {
    return SpaceBackupFromJSONTyped(json, false);
}

export function SpaceBackupFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceBackup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'running': json['running'],
        'msg': json['msg'],
        'totalItems': json['total_items'],
        'processedItems': json['processed_items'],
        'file': json['file'],
        'fileSizeKb': json['file_size_kb'],
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function SpaceBackupToJSON(json: any): SpaceBackup {
    return SpaceBackupToJSONTyped(json, false);
}

export function SpaceBackupToJSONTyped(value?: Omit<SpaceBackup, 'running'|'msg'|'total_items'|'processed_items'|'file'|'file_size_kb'|'created_by'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

