/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockUpItem } from './StockUpItem';
import {
    StockUpItemFromJSON,
    StockUpItemFromJSONTyped,
    StockUpItemToJSON,
    StockUpItemToJSONTyped,
} from './StockUpItem';

/**
 * 
 * @export
 * @interface StockUp
 */
export interface StockUp {
    /**
     * 
     * @type {Array<StockUpItem>}
     * @memberof StockUp
     */
    items: Array<StockUpItem>;
}

/**
 * Check if a given object implements the StockUp interface.
 */
export function instanceOfStockUp(value: object): value is StockUp {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function StockUpFromJSON(json: any): StockUp {
    return StockUpFromJSONTyped(json, false);
}

export function StockUpFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockUp {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StockUpItemFromJSON)),
    };
}

export function StockUpToJSON(json: any): StockUp {
    return StockUpToJSONTyped(json, false);
}

export function StockUpToJSONTyped(value?: StockUp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StockUpItemToJSON)),
    };
}

