/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One row of a bulk stock-up request (FR-F5).
 * @export
 * @interface StockUpItem
 */
export interface StockUpItem {
    /**
     * 
     * @type {number}
     * @memberof StockUpItem
     */
    food: number;
    /**
     * 
     * @type {number}
     * @memberof StockUpItem
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof StockUpItem
     */
    unit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StockUpItem
     */
    inventoryLocation?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof StockUpItem
     */
    expires?: Date | null;
}

/**
 * Check if a given object implements the StockUpItem interface.
 */
export function instanceOfStockUpItem(value: object): value is StockUpItem {
    if (!('food' in value) || value['food'] === undefined) return false;
    return true;
}

export function StockUpItemFromJSON(json: any): StockUpItem {
    return StockUpItemFromJSONTyped(json, false);
}

export function StockUpItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockUpItem {
    if (json == null) {
        return json;
    }
    return {
        
        'food': json['food'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'inventoryLocation': json['inventory_location'] == null ? undefined : json['inventory_location'],
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
    };
}

export function StockUpItemToJSON(json: any): StockUpItem {
    return StockUpItemToJSONTyped(json, false);
}

export function StockUpItemToJSONTyped(value?: StockUpItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'food': value['food'],
        'amount': value['amount'],
        'unit': value['unit'],
        'inventory_location': value['inventoryLocation'],
        'expires': value['expires'] == null ? value['expires'] : value['expires'].toISOString().substring(0,10),
    };
}

