name: Make Docs
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [working]
    types:
      - completed
  push:
    branches:
      - working

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-include-markdown-plugin
      - run: mkdocs gh-deploy --force
